version: '2.4'
services:
   aosp:
      build:
         context: ${DOCKER_IMAGE_BUILD_PATH:-./build}
         dockerfile: Dockerfile
         network: host
         args:
            username: ${DOCKER_IMAGE_USERNAME:-aosp}
            password: ${DOCKER_IMAGE_PASSWORD:-password}
      image: aosp:latest
      network_mode: host
      entrypoint: /bin/bash
      volumes:
         - type: bind
           source: ${DOCKER_VOLUME_CCACHE_PATH:-./run/cache}
           target: /home/${DOCKER_IMAGE_USERNAME:-aosp}/.cache
         - type: bind
           source: ${DOCKER_VOLUME_CCACHE_PATH:-./run/ccache}
           target: /home/${DOCKER_IMAGE_USERNAME:-aosp}/.ccache
         - type: bind
           source: ${DOCKER_VOLUME_WORKSPACE_PATH:-./run/workspace}
           target: /home/${DOCKER_IMAGE_USERNAME:-aosp}/workspace
